[package]
name = "tugger-debian"
version = "0.1.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Debian packaging primitives"
keywords = ["debian", "package", "tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.38"
ar = "0.8.0"
chrono = "0.4.19"
libflate = "1.0.3"
md5 = "0.7.0"
os_str_bytes = "2.4.0"
tar = "0.4.32"
xz2 = "0.1.6"
zstd = "0.6.0"

[dependencies.tugger-file-manifest]
version = "0.1.0-pre"
path = "../tugger-file-manifest"

[dev-dependencies]
glob = "0.3.0"
