project = 'PyOxidizer'
copyright = '2019, Gregory Szorc'
author = 'Gregory Szorc'
release = '0.1'
extensions = []
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'alabaster'
html_static_path = ['_static']
